=== Empyreans/XML-JSON-Parser/aviation.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- flight simple elements -->
    <xs:element name="departure-date" type="xs:date"/>
    <xs:element name="departure-time" type="xs:time"/>
    <xs:element name="departure-point" type="xs:string"/>
    <xs:element name="destination" type="xs:string"/>
    <xs:element name="price" type="xs:double"/>

    <!-- passenger simple elements -->
    <xs:element name="first-name" type="xs:string"/>
    <xs:element name="last-name" type="xs:string"/>
    <xs:element name="canceled" type="xs:boolean" default="false"/>

    <!-- definition of attributes -->
    <xs:attribute name="flightID" type="xs:integer"/>

    <!-- definition of complex elements -->
    <xs:element name="passenger">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="first-name"/>
                <xs:element ref="last-name"/>
                <xs:element ref="canceled"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="flight">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="departure-date"/>
                <xs:element ref="departure-time"/>
                <xs:element ref="departure-point"/>
                <xs:element ref="destination"/>
                <xs:element ref="price"/>
                <xs:element ref="passenger" maxOccurs="unbounded" minOccurs="1"/>
            </xs:sequence>
            <xs:attribute ref="flightID" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="flights">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="flight" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Empyreans/XML-JSON-Parser/aviation.xml
<?xml version="1.0" encoding="utf-8"?>
<flights xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="aviation.xsd">

    <flight flightID="1">
        <departure-date>2012-12-13</departure-date>
        <departure-time>12:12:12</departure-time>
        <departure-point>Berlin</departure-point>
        <destination>Moskau</destination>
        <price>332.99</price>
        <passenger>
            <first-name>Leon</first-name>
            <last-name>Adelberg</last-name>
            <canceled>false</canceled>
        </passenger>
        <passenger>
            <first-name>Max</first-name>
            <last-name>Regenberg</last-name>
            <canceled>false</canceled>
        </passenger>
        <passenger>
            <first-name>Theo</first-name>
            <last-name>Regenberg</last-name>
            <canceled>false</canceled>
        </passenger>
    </flight>

    <flight flightID="2">
        <departure-date>2012-12-13</departure-date>
        <departure-time>12:12:12</departure-time>
        <departure-point>Berlin</departure-point>
        <destination>Moskau</destination>
        <price>332.99</price>
        <passenger>
            <first-name>Max</first-name>
            <last-name>Mustermann</last-name>
            <canceled>false</canceled>
        </passenger>
        <passenger>
            <first-name>Rene</first-name>
            <last-name>Altenburg</last-name>
            <canceled>false</canceled>
        </passenger>
        <passenger>
            <first-name>Martha</first-name>
            <last-name>Gluecklich</last-name>
            <canceled>false</canceled>
        </passenger>
    </flight>

</flights>
